---
# https://waylonwalker.com/install-rust/
- name: check if cargo is installed
  shell: command -v cargo
  register: cargo_exists
  ignore_errors: yes

- name: Download Installer
  when: cargo_exists is failed
  get_url:
    url: https://sh.rustup.rs
    dest: "{{ lookup('env', 'HOME') }}/sh.rustup.rs"
    mode: '0755'
    force: 'yes'

- name: install rust/cargo
  when: cargo_exists is failed
  shell: "{{ lookup('env', 'HOME') }}/sh.rustup.rs -y"

# TODO: delete tmp/ file
# TODO: is the lookup necessary with no become?
