---
#-------------- Role: default --------------#
apt_cache_time: 3600

apt_packages:
  - ca-certificates
  - curl
  - gh  # for `gh auth login`
  - git
  - gnupg
  - grep
  - htop
  - openssl
  - vim

#-------------- Role: vscode --------------#
vscode_extensions:
  - davidanson.vscode-markdownlint  # markdown lint
  - equinusocio.vsc-material-theme-icons  # material icon theme
  # - johnpapa.vscode-peacock  # peacock - add colours to your windows
  - littlefoxteam.vscode-python-test-adapter  # python test explorer
  - mhutchie.git-graph  # git graph
  - ms-azuretools.vscode-docker  # docker
  - ms-python.debugpy # python debugger
  - ms-python.python  # python
  - ms-python.vscode-pylance  # pylance
  - golang.go  # go
  - tamasfe.even-better-toml  # toml linting

#-------------- Role: geerlingguy.dotfiles --------------#
# https://github.com/geerlingguy/ansible-role-dotfiles
configure_dotfiles: true

dotfiles_repo: https://github.com/BenWolfaardt/Dotfiles.git
dotfiles_repo_version: main
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/src/config/dotfiles
dotfiles_home: "~"
dotfiles_files:
  - .gitconfig
  - .gitignore
  - .zprofile
  - .zshenv
  - .zshrc
