---
#-------------- Role: default --------------#
apt_cache_time: 3600

apt_packages:
  - ca-certificates
  - curl
  - gh  # for `gh auth login`
  - git
  - gnupg
  - grep
  - htop
  - openssl
  # - postgresql@15
  - vim

ppa_packages:
  # - ppa:atareao/telegram
  # - ppa:ubuntu-mozilla-security/ppa

#-------------- Role: vscode --------------#
vscode_extensions:
  - mhutchie.git-graph  # git graph
  - ms-azuretools.vscode-docker  # docker
  - ms-python.python  # python
  - ms-python.vscode-pylance  # pylance
  - golang.go  # go
  - tamasfe.even-better-toml  # toml linting

#-------------- Role: geerlingguy.dotfiles --------------#
# https://github.com/geerlingguy/ansible-role-dotfiles
configure_dotfiles: true

dotfiles_repo: https://github.com/BenWolfaardt/Dotfiles.git
dotfiles_repo_version: main
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/src/config/dotfiles
dotfiles_home: "~"
dotfiles_files:
  - .gitconfig
  - .gitignore
  - .zprofile
  - .zshenv
  - .zshrc
