---
#--------------Role: Homebrew --------------#
# formulae
homebrew_installed_packages:
  # - ansible  # installed with bin/bootstrap command to make our lives easy
  # - build-essential  # installed with bin/bootstrap command as it is a pre-requisite to brew
  # - curl  # installed with bin/bootstrap command as it is a pre-requisite to brew
  # - docker
  # - docker-compose
  # - file  # installed with bin/bootstrap command as it is a pre-requisite to brew
  # - gcc  # installed with bin/bootstrap command as it is a recommended first step by brew
  # - git  # installed with bin/bootstrap command as it is a pre-requisite to brew
  - grep
  - htop
  - openssl@1.1
  - poetry
  - postgresql@15
  # - procps  # installed with bin/bootstrap command as it is a pre-requisite to brew
  - pyenv
  - pyenv-virtualenv
  - python@3.11
  - wget
  # - zsh  # installed with bin/bootstrap command to make our lives easy

#-------------- Role: geerlingguy.dotfiles --------------#
# https://github.com/geerlingguy/ansible-role-dotfiles
configure_dotfiles: true

dotfiles_repo: https://github.com/BenWolfaardt/Dotfiles.git
dotfiles_repo_version: main
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/src/config/dotfiles
dotfiles_home: "~"
dotfiles_files:
  - .gitconfig
  - .gitignore
  - .zprofile
  - .zshenv
  - .zshrc
