---
#-------------- Role: default --------------#
apt_cache_time: 3600

apt_packages:
  - ca-certificates
  - curl
  - gh  # for `gh auth login` - # TODO: results in poor SSH names
  - git
  - gnupg
  - grep
  - haveged
  - htop
  - ipv6calc
  - jq
  - net-tools
  - nmap
  - openssl
  - postgresql-client
  - tmux
  - whois
  - vim

#-------------- Role: ignite --------------#
ignite_version: "v0.27.2"

#-------------- Role: go --------------#
go_version: "1.21.12"
go_tarball: "go{{ go_version }}.linux-amd64.tar.gz"
go_url: "https://go.dev/dl/{{ go_tarball }}"

#-------------- Role: vscode --------------#
vscode_extensions:
  - davidanson.vscode-markdownlint  # markdown lint
  - dbaeumer.vscode-eslint  # es lint
  - equinusocio.vsc-material-theme-icons  # material icon theme
  # - github.vscode-github-actions  # github actions
  - golang.go  # go
  - hashicorp.terraform  # terraform
  - juanblanco.solidity  # solidity
  # - johnpapa.vscode-peacock  # peacock - add colours to your windows
  - littlefoxteam.vscode-python-test-adapter  # python test explorer
  - mhutchie.git-graph  # git graph
  - ms-azuretools.vscode-docker  # docker
  - ms-vscode.live-server  # live html previewer
  - ms-python.debugpy # python debugger
  - ms-python.python  # python
  - ms-python.vscode-pylance  # pylance
  - ms-vscode.makefile-tools  # Makefile Tools
  # - peterj.proto  # proto
  # - rust-lang.rust-analyzer  # rust
  - tamasfe.even-better-toml  # toml linting
  - tomoki1207.pdf  # pdf viewer
  # - yoavbls.pretty-ts-errors  # pretty ts errors
  - zxh404.vscode-proto3  # proto3

#-------------- Role: geerlingguy.dotfiles --------------#
# https://github.com/geerlingguy/ansible-role-dotfiles
configure_dotfiles: true

dotfiles_repo: https://github.com/BenWolfaardt/Dotfiles.git
dotfiles_repo_version: main
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/src/config/dotfiles
dotfiles_home: "~"
dotfiles_files:
  - .gitconfig
  - .gitignore
  - .p10k.zsh
  - .zprofile
  - .zshenv
  - .zshrc
