---
- name: Configure Ubuntu
  hosts: localhost
  
  vars_files:
    - defaults.config.yml

  roles:
    # - role: default
    #   tags: [default]

    # - role: bitwarden  # working
    #   tags: [bitwarden]
    # - role: brave  # working
    #   tags: [brave]
    # - role: dbeaver  # working
    #   tags: [dbeaver]
    # - role: cosmos  # working
    #   tags: [cosmos]
    # - role: discord  # working
    #   tags: [discord]
    # - role: docker  # working
    #   tags: [docker]
    # - role: go  # working
    #   tags: [go]
    # - role: libfuse  # working
    #   tags: [libfuse]
    # - role: nvm  # working
    #   tags: [nvm]
    # - role: obsidian  # working
    #   tags: [obsidian]
    # - role: poetry  # working
    #   tags: [poetry]    
    # - role: postman  # working
    #   tags: [postman]
    # - role: pyenv  # working
    #   tags: [pyenv]
    # - role: rust  # working
    #   tags: [rust]
    # - role: slack  # working
    #   tags: [slack]
    # - role: snapd  # potentially have as a default - enable by default - how does that affect main
    #   tags: [snapd]
    # - role: solaar  # working
    #   tags: [solaar]
    # - role: stretchly  # working
    #   tags: [stretchly]
    # - role: teamviewer
    #   tags: [teamviewer]
    # - role: terraform  # working
    #   tags: [terraform]
    # - role: vlc  # working
    #   tags: [vlc]
    # - role: vscode  # working
    #   tags: [vscode]
    # - role: wezterm  # working
    #   tags: [wezterm]
    # - role: zsh  # working
    #   tags: [zsh]
    # - role: geerlingguy.dotfiles  # pyenv needs to be installed first
    #   when: configure_dotfiles
    #   tags: ['dotfiles']
