---
- name: Add the Microsoft GPG key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Add the Visual Studio Code repository
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    state: present

- name: Install Visual Studio Code
  apt:
    name: code
    state: present
    update_cache: yes
  become: yes

- name: Install Visual Studio Code extensions
  command: code --install-extension {{ item }}
  with_items: "{{ vscode_extensions }}"
  ignore_errors: yes