---
- name: Install {{ homebrew_formulae }} formulae with 'brew' in default path
  shell: brew install {{ item }}
  loop: "{{ homebrew_formulae }}"

# This isn't in my dotfiles repo as it is Linux specific and I don't want a branch per OS
- name: Add brew to the .zprofle
  shell: |
    echo '' >> /home/ben/.zprofile
    echo '# Set PATH, MANPATH, etc., for Homebrew.' >> /home/ben/.zprofile
    echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> /home/ben/.zprofile