---
- name: Fetch the latest Obsidian release URL
  shell: >
    wget -q -O - https://api.github.com/repos/obsidianmd/obsidian-releases/releases/latest |
    grep 'deb"$' |
    awk -F'"' '{print $4}'
  register: obsidian_download_url
  args:
    chdir: "{{ download_directory }}"
  changed_when: False

- name: Download the Obsidian .deb package
  get_url:
    url: "{{ obsidian_download_url.stdout }}"
    dest: "{{ download_directory }}/{{ deb_file }}"
    mode: '0644'

- name: Install Obsidian .deb package
  apt:
    deb: "{{ download_directory }}/{{ deb_file }}"
  become: yes

- name: Ensure all dependencies are installed
  apt:
    update_cache: yes
    # fix_broken: yes  # TODO figure out
  become: yes

- name: Remove the downloaded .deb file
  file:
    path: "{{ download_directory }}/{{ deb_file }}"
    state: absent
