---
# TODO: run default first?
# - name: Ensure git is installed
#   ansible.builtin.package:
#     name: git
#     state: present

- name: Clone goenv repository
  ansible.builtin.git:
    repo: 'https://github.com/go-nv/goenv.git'
    dest: '~/.goenv'
    update: yes
