---
- name: Python prerequisites
  apt:
    name:
      - build-essential
      - libssl-dev
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev 
      - curl
      - libncursesw5-dev
      - xz-utils
      - tk-dev 
      - libxml2-dev
      - libxmlsec1-dev
      - libffi-dev
      - liblzma-dev
    state: present
  become: yes

- name: Check if Pyenv is already installed
  stat:
    path: /home/ben/.pyenv
  register: pyenv_dir

- name: Install Pyenv
  shell: curl https://pyenv.run | bash
  when: not pyenv_dir.stat.exists

# Add pyenv to terminal config
#   My dotfiles: https://github.com/BenWolfaardt/Dotfiles are automatically pulled with the 
#   https://github.com/geerlingguy/ansible-role-dotfiles Ansible role
