---
- name: Install pyenv
  shell: curl https://pyenv.run | bash

# Already in dotfiles: https://github.com/BenWolfaardt/Dotfiles
# - name: Add pyenv path to .zshrc
#   shell: |
#     echo '\n' >> /home/ben/.zshrc
#     echo '# Set PATH for pyenv.' >> /home/ben/.zshrc
#     echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.zshrc
#     echo 'command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.zshrc
#     echo 'eval "$(pyenv init -)"' >> ~/.zshrc

# Already in dotfiles: https://github.com/BenWolfaardt/Dotfiles
# - name: Add pyenv to .zprofile
#   shell: |
#     echo '\n' >> /home/ben/.zprofile
#     echo '# Set PATH for pyenv.' >> /home/ben/.zprofile
#     echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.zprofile
#     echo 'command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.zprofile
#     echo 'eval "$(pyenv init -)"' >> ~/.zprofile
